package com.wang.learn.domain.admin;

import java.util.Date;

public class MallApp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.mall_app_id
     *
     * @mbggenerated
     */
    private Long mallAppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.modified_time
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.is_enable
     *
     * @mbggenerated
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.mall_app_name
     *
     * @mbggenerated
     */
    private String mallAppName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.mall_type
     *
     * @mbggenerated
     */
    private Byte mallType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.app_secret
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.service_url
     *
     * @mbggenerated
     */
    private String serviceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.callback_url
     *
     * @mbggenerated
     */
    private String callbackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_mall_app.safety_certificate
     *
     * @mbggenerated
     */
    private String safetyCertificate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.mall_app_id
     *
     * @return the value of admin_mall_app.mall_app_id
     *
     * @mbggenerated
     */
    public Long getMallAppId() {
        return mallAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.mall_app_id
     *
     * @param mallAppId the value for admin_mall_app.mall_app_id
     *
     * @mbggenerated
     */
    public void setMallAppId(Long mallAppId) {
        this.mallAppId = mallAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.modified_time
     *
     * @return the value of admin_mall_app.modified_time
     *
     * @mbggenerated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.modified_time
     *
     * @param modifiedTime the value for admin_mall_app.modified_time
     *
     * @mbggenerated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.created_time
     *
     * @return the value of admin_mall_app.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.created_time
     *
     * @param createdTime the value for admin_mall_app.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.is_enable
     *
     * @return the value of admin_mall_app.is_enable
     *
     * @mbggenerated
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.is_enable
     *
     * @param isEnable the value for admin_mall_app.is_enable
     *
     * @mbggenerated
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.mall_app_name
     *
     * @return the value of admin_mall_app.mall_app_name
     *
     * @mbggenerated
     */
    public String getMallAppName() {
        return mallAppName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.mall_app_name
     *
     * @param mallAppName the value for admin_mall_app.mall_app_name
     *
     * @mbggenerated
     */
    public void setMallAppName(String mallAppName) {
        this.mallAppName = mallAppName == null ? null : mallAppName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.mall_type
     *
     * @return the value of admin_mall_app.mall_type
     *
     * @mbggenerated
     */
    public Byte getMallType() {
        return mallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.mall_type
     *
     * @param mallType the value for admin_mall_app.mall_type
     *
     * @mbggenerated
     */
    public void setMallType(Byte mallType) {
        this.mallType = mallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.app_key
     *
     * @return the value of admin_mall_app.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.app_key
     *
     * @param appKey the value for admin_mall_app.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.app_secret
     *
     * @return the value of admin_mall_app.app_secret
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.app_secret
     *
     * @param appSecret the value for admin_mall_app.app_secret
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.service_url
     *
     * @return the value of admin_mall_app.service_url
     *
     * @mbggenerated
     */
    public String getServiceUrl() {
        return serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.service_url
     *
     * @param serviceUrl the value for admin_mall_app.service_url
     *
     * @mbggenerated
     */
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl == null ? null : serviceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.callback_url
     *
     * @return the value of admin_mall_app.callback_url
     *
     * @mbggenerated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.callback_url
     *
     * @param callbackUrl the value for admin_mall_app.callback_url
     *
     * @mbggenerated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_mall_app.safety_certificate
     *
     * @return the value of admin_mall_app.safety_certificate
     *
     * @mbggenerated
     */
    public String getSafetyCertificate() {
        return safetyCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_mall_app.safety_certificate
     *
     * @param safetyCertificate the value for admin_mall_app.safety_certificate
     *
     * @mbggenerated
     */
    public void setSafetyCertificate(String safetyCertificate) {
        this.safetyCertificate = safetyCertificate == null ? null : safetyCertificate.trim();
    }
}