package com.wang.learn.consumer.dao.oms;

import com.wang.learn.consumer.domain.oms.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    List<User> selectAllUser();
}